# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='usage_ratio',
        ),
        migrations.AddField(
            model_name='location',
            name='usage_percentage',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='current_ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='batches.Ingredient'),
        ),
    ]
