# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0002_auto_20170313_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='usage_percentage',
        ),
        migrations.AddField(
            model_name='location',
            name='usage_ratio',
            field=models.IntegerField(default=1),
        ),
    ]
