# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0003_auto_20170314_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='volume',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='drop',
            name='volume',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
