# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0004_auto_20170324_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='order_ref',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
