# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0005_batch_order_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('AGG', 'Aggregate'), ('CEM', 'Cement'), ('ADD', 'Additive'), ('WAT', 'Water'), ('OTH', 'Other')], default='AGG', max_length=3),
        ),
    ]
