# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0006_auto_20170326_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
